- app/models/favorite.rb
- app/models/genre.rb
- app/models/genres_review.rb
- app/models/place.rb
- app/models/review.rb
- db/migrate/20200824195615_create_genres.rb
- db/migrate/20200824200131_create_places.rb
- db/migrate/20200824200503_create_reviews.rb
- db/migrate/20200824201916_create_genres_reviews.rb
- db/migrate/20200824202605_create_favorites.rb
- test/models/favorite_test.rb
- test/models/genre_test.rb
- test/models/genres_review_test.rb
- test/models/place_test.rb
- test/models/review_test.rb
Created
-place model
-genre model
-favorite model
-genre_reeview model
-review model
plus the migrations, (**without geocode**), please check them
> Created basic models plus migrations

- app/controllers/places_controller.rb
- app/controllers/reviews_controller.rb
- app/controllers/users_controller.rb
- app/views/places/index.html.erb
- app/views/places/show.html.erb
- config/routes.rb
- test/controllers/places_controller_test.rb
- test/controllers/reviews_controller_test.rb
- test/controllers/users_controller_test.rb
> Basic controllers/views

- app/models/review.rb
- db/migrate/20200825200857_remove_ragins_from_genres_reviews.rb
- db/migrate/20200825201023_add_rating_to_reviews.rb
- db/schema.rb
Added rating to the reviews table, removed it from the genres_reviews 
Cheers
> Changed schema, review controller

- app/controllers/places_controller.rb
- app/models/place.rb
- app/models/user.rb
- db/migrate/20200826161618_add_user_to_places.rb
- db/schema.rb
Changed Place table > added reference to a user (belongs_to :user on the model)
Changed User model > has_many :places
> Changed schema

- app/assets/stylesheets/config/_colors.scss
- app/views/places/new.html.erb
- app/views/shared/_form.html.erb
added to color palette and added new categories to new place form. Not finished yet, but started.
> New place form

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_homepage.scss
- app/assets/stylesheets/components/_index.scss
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
- package.json
- yarn.lock
v1 design, remember to yarn install, bundle install
> Basic homepage mobile design.

- app/assets/stylesheets/components/_homepage.scss
- app/views/pages/home.html.erb
> Show genres page

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/components/_homepage.scss
- app/assets/stylesheets/components/_places_photo.scss
- app/assets/stylesheets/components/_reviews.scss
- app/controllers/places_controller.rb
- app/controllers/reviews_controller.rb
- app/javascript/packs/application.js
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
- app/views/places/index.html.erb
- app/views/places/show.html.erb
review form and genre review back end works, still need front end
> Review button and form, genres reviews added

- app/assets/stylesheets/components/_form.scss
- app/views/shared/_form.html.erb
- db/seeds.rb
finished styling the photo button
> finished styling the new-place-form

- app/javascript/packs/application.js
- app/javascript/packs/searchgenre.js
- app/views/layouts/application.html.erb
- app/views/shared/_form.html.erb
There was a file that wasn't working for a function so I'm taking it out completely and will replace with a new one.
> taking out the javascript

- app/views/devise/registrations/new.html.erb
- app/views/layouts/application.html.erb
- app/views/shared/_form.html.erb
this is still not finished, but I gotta go get dinner!
> Log in form

- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_links.html.erb
still would like to fix the links at the bottom but moving on because it's not that important today.
> styled log-in form

- app/assets/stylesheets/components/_index_page.scss
- app/views/pages/home.html.erb
- app/views/places/index.html.erb
Plus removed text decoration from index page
> Finished some touches for the homepage

- app/javascript/packs/application.js
- app/javascript/plugins/init_select2.js
- app/views/layouts/application.html.erb
- app/views/shared/_form.html.erb
- package.json
- yarn.lock
> Adding select2 to genre search

- app/assets/stylesheets/components/_form.scss
- app/javascript/packs/application.js
- app/javascript/plugins/init_autocomplete.js
- app/views/shared/_form.html.erb
- package.json
- yarn.lock
Added places.js , remember to yarn install!
> Added algoliaPlaces for address

- app/assets/stylesheets/components/_homepage.scss
- app/assets/stylesheets/config/_bootstrap_variables.scss
- app/views/pages/home.html.erb
the landing page is more aligned to teacher's advice from demo day, but the cards are all messed up. but near done!
> this landing page is better, but not finished

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_map.scss
- app/javascript/plugins/init_mapbox.js
- app/views/shared/_navbar.html.erb
- package.json
- yarn.lock
> Search feature on the mapbox

- app/assets/stylesheets/components/_homepage.scss
- app/views/pages/home.html.erb
did the landing page and modal so that it's responsive to screen size. It's still not perfect, but much more responsive and readable and what our advisors were looking for.
> mostly done with landing page and modal

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/application.scss
- app/controllers/places_controller.rb
- app/javascript/packs/application.js
- app/policies/application_policy.rb
- app/policies/place_policy.rb
- app/services/executable.rb
- app/services/spotify_access_token_fetcher.rb
- app/views/places/connect.html.erb
- app/views/places/edit.html.erb
- config/routes.rb
i hope this doesn't break later :3
> Spotifyapi

- app/assets/stylesheets/components/_map.scss
- app/views/places/index.html.erb
> map stuff plus profile asdfasdg

- app/views/shared/_media-overlay.html.erb
> updated language on banner display
